# The code imports and formats the data
# Requires matrix.txt and count.txt generated by the pre-processing steps
# and labels.txt from the data RawSamples folder
# All three txt files should be put in the same folder as this R file
setwd("~/")

# Strike-related: label 0; not-related: label 1.
matrix=read.table("matrix.txt")
GDQ1 = matrix[1:2500,]
GDQ2 = matrix[2501:5000,]
GDQ3 = matrix[5001:7500,]
GDQ4 = matrix[7501:10000,]
NGD  = matrix[10001:12500,]

label = read.table("labels.txt")
labelGDQ1=label[1:2500,]
labelGDQ2=label[2501:5000,]
labelGDQ3=label[5001:7500,]
labelGDQ4=label[7501:10000,]
labelNGD = label[10001:12500,]
A = GDQ1[labelGDQ1==0,]
B = GDQ1[labelGDQ1==1,]
save(A,B,file="dataGDQ1.RData")
A = GDQ2[labelGDQ2==0,]
B = GDQ2[labelGDQ2==1,]
save(A,B,file="dataGDQ2.RData")
A = GDQ3[labelGDQ3==0,]
B = GDQ3[labelGDQ3==1,]
save(A,B,file="dataGDQ3.RData")
A = GDQ4[labelGDQ4==0,]
B = GDQ4[labelGDQ4==1,]
save(A,B,file="dataGDQ4.RData")
A = NGD[labelNGD==0,]
B = NGD[labelNGD==1,]
save(A,B,file="dataNGD.RData")

count = read.table("count.txt")
save(count, file="count.RData")
